apiVersion: apps/v1
kind: Deployment
metadata:
  name: genkart-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: genkart-client
  template:
    metadata:
      labels:
        app: genkart-client
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.client.repository }}:{{ .Values.image.client.tag }}"
          imagePullPolicy: {{ .Values.image.client.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: genkart-client-secrets
          resources:
            {{- toYaml .Values.resources.client | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: genkart-client
spec:
  selector:
    app: genkart-client
  ports:
    - protocol: TCP
      port: {{ .Values.service.client.port }}
      targetPort: 3000
  type: {{ .Values.service.client.type }}
