# Grafana values for basic dashboard setup in GKE
adminPassword: admin
service:
  type: LoadBalancer
  port: 30001
persistence:
  enabled: false
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.default.svc.cluster.local:9090
        isDefault: true
rbac:
  create: true
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m
