# values.yaml

replicaCount: 2

image:
  client:
    repository: chirag117/gen-client
    tag: 'v1'
    pullPolicy: IfNotPresent
  server:
    repository: chirag117/gen-serv
    tag: 'v1'
    pullPolicy: IfNotPresent

service:
  client:
    type: LoadBalancer
    port: 3000
  server:
    type: ClusterIP   # Server can remain ClusterIP, client will talk to it internally
    port: 5555

resources:
  client:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  server:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: false # <--- CHANGE THIS TO DISABLE INGRESS
  # className: "nginx"
  # host: "genkart.com"
  # tls:
  #   secretName: "genkart-tls"
  # annotations:
  #   kubernetes.io/ingress.class: "nginx"
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"

# Example secrets (base64-encoded, override via --set or values-secret.yaml)
secrets:
  client: {}
  server: {}